---
- name: Install required packages
  become: yes
  apt:
    update_cache: yes
    state: present
    name:
      - make
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - wget
      - curl
      - llvm
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libxml2-dev
      - libxmlsec1-dev
      - libffi-dev
      - liblzma-dev

- name: Download and install pyenv
  become: yes
  become_user: ldraney
  shell: curl https://pyenv.run | bash
  args:
    creates: /home/ldraney/.pyenv
  environment:
    HOME: /home/ldraney
    USER: ldraney
    PATH: /home/ldraney/.pyenv/bin:/home/ldraney/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games

- name: Set PYENV_ROOT environment variable
  become: yes
  become_user: ldraney
  lineinfile:
    path: /home/ldraney/.bashrc
    line: 'export PYENV_ROOT="$HOME/.pyenv"'
    state: present

- name: Add pyenv to PATH
  become: yes
  become_user: ldraney
  lineinfile:
    path: /home/ldraney/.bashrc
    line: 'export PATH="$PYENV_ROOT/bin:$PATH"'
    state: present

- name: Add pyenv init to bashrc
  become: yes
  become_user: ldraney
  lineinfile:
    path: /home/ldraney/.bashrc
    line: 'eval "$(pyenv init --path)"'
    state: present

- name: Add pyenv virtualenv-init to bashrc
  become: yes
  become_user: ldraney
  lineinfile:
    path: /home/ldraney/.bashrc
    line: 'eval "$(pyenv virtualenv-init -)"'
    state: present

- name: Install pyenv dependencies and set global version
  become: yes
  become_user: ldraney
  shell: |
    export PYENV_ROOT="$HOME/.pyenv"
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init --path)"
    eval "$(pyenv virtualenv-init -)"
    pyenv install {{ pyenv_version }}
    pyenv global {{ pyenv_version }}
  environment:
    HOME: /home/ldraney
    USER: ldraney
    PATH: /home/ldraney/.pyenv/bin:/home/ldraney/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
  args:
    creates: /home/ldraney/.pyenv/versions/{{ pyenv_version }}

- name: Install libtmux
  become: yes
  become_user: ldraney
  pip:
    name: libtmux
    executable: /home/ldraney/.pyenv/shims/pip
  environment:
    HOME: /home/ldraney
    USER: ldraney
    PATH: /home/ldraney/.pyenv/shims:/home/ldraney/.pyenv/bin:/home/ldraney/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games

