- name: make directory for dotfiles
  become_user: ldraney
  ignore_errors: yes
  ansible.builtin.file:
    path: /home/ldraney/{{ item }}
    state: directory
    mode: '0755'
  with_items:
    - .local/share/nvim/site/autoload
    - .config
    - .config/nixpkgs

- name: sensitive files symlinks
  ignore_errors: yes
  become_user: ldraney
  ansible.builtin.file:
    src: '/home/ldraney/github/sensitive/{{ item.src }}'
    dest: '/home/ldraney/{{ item.dest }}'
    state: link
    force: true
  loop:
    - { src: 'zsh/zsh_history', dest: '.zsh_history' }
    - { src: 'zsh/zshenv', dest: '.zshenv' }
    - { src: 'vim', dest: '.vim' }
    - { src: 'ansible/ansible.cfg', dest: '.ansible.cfg' }

- name: neovim root link
  ignore_errors: yes
  ansible.builtin.file:
    src: '/home/ldraney/github/dotfilesWSL/{{ item.src }}'
    dest: '/{{ item.dest }}'
    state: link
  loop:
    - { src: 'nvim/nvim-linux64/bin/nvim', dest: 'usr/bin/vim' }

#- name: clone ssh_keys
  #ignore_errors: yes
  #become_user: ldraney
  #ansible.builtin.git:
    #repo: 'ssh://git@github.com/ldraney/sensitive.git'
    #update: yes
    #clone: yes
    #dest: /home/ldraney/github/sensitive
    #key_file: /home/ldraney/.ssh/id_ed25519
    #accept_hostkey: yes
    #
#- name: copy ssh keys
  #ignore_errors: yes
  #copy:
    #src: /home/ldraney/github/sensitive/ssh
    #dest: /home/ldraney/.ssh
    #owner: ldraney
    #group: ldraney
    #mode: 400
      #- name: Evaluating the authentication agent & adding the keys...
      #  become_user: ldraney
      #  shell:
      #    cmd: {{ item }}
      #  with_items: 
      #    - eval "$(ssh-agent)"
      #    - ssh-add ~/.ssh/id_rsa
      #    - ssh-add ~/.ssh/id_ed25519

#- name: remove files to make room for new symlinks
#  file: 
#    path: '{{ item }}'
#    state: absent
#  with_items:
#    - /home/ldraney/.oh-my-zsh
#    - /home/ldraney/.ssh
#
##- name: delete old .vim directory
  #file:
    #state: absent
    #path: /home/ldraney/.vim
    #
