- name: install python2 
  package: 
    name: python2

- name: download pip2
  #ignore_errors: yes
  #become_user: ldraney
  ansible.builtin.get_url:
    dest: /home/ldraney/recon/tv/dev-setup/setupTvp/get-pip.py
    url: https://bootstrap.pypa.io/pip/2.7/get-pip.py

- name: install pip2
  become_user: ldraney
  shell: 'sudo python2 /home/ldraney/recon/tv/dev-setup/setupTvp/get-pip.py'

- name: Run a install script using python2 to install pip2
  ansible.builtin.script: /home/ldraney/recon/tv/dev-setup/setupTvp/get-pip.py
  args:
    executable: python2

- name: pip install tvp dependencies
  pip:
    requirements: /home/ldraney/recon/tv/dev-setup/setupTvp/requirements.txt
    executable: pip2

